version: '3.9'
services:
  database:
    container_name: database
    image: postgres
    command: postgres -c shared_preload_libraries=pgaudit -c ssl=${C_SSL_ON:-off} -c ssl_cert_file=$C_SSL_CERT_F -c ssl_key_file=$C_SSL_KEY_F
    ports:
      - 5432:5432
    restart: always
    volumes:
      - './db-data:/var/lib/postgresql/data'
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-semsenha}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-ticketplace-db}
    networks:
      - ticketplace

# Keep this network configuration to allow the containers to communicate with each other
# in case of `host.docker.internal` not working
networks:
  ticketplace:
    driver: bridge
    ipam:
      config:
        # 16 IPs 192.168.50.0 - 192.168.50.15 - 14 usable IPs
        - subnet: 192.168.50.0/28
