Table "tb_empresa" {
  "id" serial [not null, increment]
  "name" varchar(255) [not null]
  "cnpj" varchar(14) [pk, not null]
  "email" varchar(255) [not null]
  "created_at" timestamptz [not null, default: `current_timestamp`]
  "updated_at" timestamptz [not null, default: `current_timestamp`]
}

Table "tb_eventos" {
  "id" bigint [pk, not null]
  "title" varchar(255) [not null]
  "description" text [not null]
  "value" float [not null]
  "created_at" timestamptz [not null, default: `current_timestamp`]
  "updated_at" timestamptz [not null, default: `current_timestamp`]
}

Table "tb_ingressos" {
  "id" bigint [pk, not null]
  "value" float [not null]
  "id_evento" bigint [not null]
  "id_usuario" bigint [not null]
  "created_at" timestamptz [not null, default: `current_timestamp`]
  "updated_at" timestamptz [not null, default: `current_timestamp`]
}

Table "tb_usuarios" {
  "id" bigint [not null]
  "name" varchar(255) [not null]
  "cpf" varchar(11) [not null]
  "email" varchar(255) [pk, not null]
  "password" varchar(255) [not null]
  "created_at" timestamptz [not null, default: `current_timestamp`]
  "updated_at" timestamptz [not null, default: `current_timestamp`]
}

Table "tb_dados_cartao" {
  "id" bigint [not null]
  "titula_cartao" varchar(225) [not null]
  "cpf_titular" varchar(11) [not null]
  "numero_cartao" varchar(255) [pk, not null]
  "data_expiracao" timestamptz [not null]
  "codigo_seguranca" varchar(4) [not null]
  "id_usuario" bigint [not null]
  "created_at" timestamptz [not null, default: `current_timestamp`]
  "updated_at" timestamptz [not null, default: `current_timestamp`]
}

Table "tb_pagamentos" {
  "id" bigint [pk, not null]
  "quantidade_ingressos" int [not null]
  "valo_final" float [not null]
  "id_usuario" bigint [not null]
  "id_ingresso" bigint [not null]
  "created_at" timestamptz [not null, default: `current_timestamp`]
  "updated_at" timestamptz [not null, default: `current_timestamp`]
}

